### ISSUE TITLE
markdown公式显示的是LaTeX代码？

### ISSUE THREAD

**Issue by yokeman-young** [slowdivePTG/Notes#10]
我在看你笔记的时候，发现公式部分展现的是LaTeX代码，难道GitHub不支持laTeX在markdown上？

**Comment by AstroJacobLi** [comment]
（代repo主回答一下）
GitHub原生不支持Mathjax的相关功能。如果您使用Chrome浏览器，可以安装MathJax Plugin for Github插件，之后可以在chrome里显示部分代码。
https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima
除此之外，您可以将repo clone到本地，用Markdown编辑器查看公式。

**Comment by slowdivePTG** [comment]
是的，建议您下载到本地。已经在 Readme 中说明。
